version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ${DB_VOLUME}
      - ./db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres_trabalho_ben10", "-d", "postgres_ben10"]
      interval: 10s
      timeout: 5s
      retries: 5

  game:
    container_name: game
    build:
      context: ..
      dockerfile: docker/dockerfile
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
