FROM python:3.10-slim

USER root

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /home/app

COPY ./server .

RUN pip install --no-cache-dir --user -r requirements.txt

CMD [ "python3", "app.py" ]